services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "some_pass_some_pass123!"
    ports:
      - "1433:1433"
    volumes:
      - vmnova-data:/var/opt/mssql

volumes:
  vmnova-data:
